# -*- coding: utf-8 -*-
"""Z4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDL34KnF02HwiOIPl49_IFRhs8mRiKfl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Generate dummy data for global CO2 emissions
years = range(2000, 2021)
sectors = ['Energy', 'Industry', 'Transportation', 'Residential', 'Commercial', 'Agriculture']
countries = ['Country A', 'Country B', 'Country C', 'Country D', 'Country E']

# Create DataFrame for global CO2 emissions
co2_emissions_data = np.random.uniform(1000, 5000, (len(years), len(sectors)))
co2_emissions_df = pd.DataFrame(co2_emissions_data, index=years, columns=sectors)

# Summary Statistics
co2_summary_stats = co2_emissions_df.describe().loc[['mean', 'std', 'min', 'max']]

# Plot: Global CO2 Emissions by Sector Over Time (Bar Plots)
plt.figure(figsize=(12, 8))
for sector in sectors:
    plt.bar(co2_emissions_df.index, co2_emissions_df[sector], label=sector)
plt.title('Global CO2 Emissions by Sector Over Time')
plt.xlabel('Year')
plt.ylabel('CO2 Emissions (MtCO2)')
plt.legend()
plt.grid(axis='y')
plt.savefig('global_co2_emissions_by_sector_bar.png')
plt.show()

# Plot: Top CO2 Emitting Countries Over Time (Line Plot)
top_countries = co2_emissions_df.mean().nlargest(3).index
plt.figure(figsize=(10, 6))
for country in top_countries:
    plt.plot(co2_emissions_df.index, co2_emissions_df.loc[:, country], marker='o', label=country)
plt.title('Top CO2 Emitting Countries Over Time')
plt.xlabel('Year')
plt.ylabel('CO2 Emissions (MtCO2)')
plt.legend()
plt.grid(True)
plt.savefig('top_co2_emitting_countries_over_time_line.png')
plt.show()

# Summary Statistics Table
co2_summary_stats.to_csv('summary_statistics_co2_emissions.csv')

# Print Summary Statistics
print(co2_summary_stats)